const games = [
  "Akumu 🏚",
  "Apeirophobia 👣",
  "ABC Lore",
  "ALBERT Doors ✨✌🏻",
  "Bakon 🥓👨",
  "BEAR 🐻",
  "Before Truth 🏚",
  "Bewildered 🌲",
  "Banana Eats 🍌",
  "Cheese Escape 🧀",
  "Centipede",
  "Doe 🔪",
  "Dead Realm 🔪",
  "Dead Silence 👁",
  "Deepwoken 🎃",
  "Disturbance",
  "Dog! 😨🐶",
  "Doors 🚪👁",
  "Doors Floor 2 🚪",
  "Endless Doors 🚪",
  "Escape the Darkness 🕛🔪",
  "Eyes the Horror Game",
  "Evade",
  "ELMIRA",
  "Evelyn",
  "Eternal Insolence",
  "Frogge 🐸",
  "FNAF: Coop 🍕",
  "Faith",
  "Frigid Dusk",
  "Forsaken 🔪",
  "Floppy Playtime 🛝",
  "Gerald!",
  "Granny 👵🏽",
  "Insane Elevator 🛗",
  "Imagine",
  "Infectious Smile 😀",
  "JUDY 💅✨",
  "Little Ones 📌",
  "Minus Elevation",
  "Midnight Hours 🕛",
  "Mommy 👩‍👧",
  "Night of Noobs",
  "Nanny 🙈",
  "Nico Nextbots",
  "Panik 🦾",
  "Puppet 🧸",
  "Piggy 🐷",
  "Piggy 2 🐷",
  "Questy",
  "Ronald 🤡",
  "Rickey Rat 🐀",
  "Rainbow Friends 🌈",
  "Rainbow Friends 2 🌈",
  "Slimey",
  "Survive The Killer 🕛 🔪",
  "SCP Games 😶‍🌫️",
  "Short Creepy Stories 📚",
  "Specter",
  "School 🎃",
  "Submarine Simulator 🌊",
  "The Horror Mansion 🏠",
  "Teddy Modded 🐼",
  "Teddy Friends 🧸",
  "The Catcher 🐱",
  "The Mirror 🪞",
  "The Circus 🎪",
  "Trespass 🏚",
  "The Dead 💀",
  "The Tall Man 👨",
  "The Truth Untold",
  "The Asylum ❄️",
  "The Schoolhouse 🏫",
  "The Mimic",
  "Us Are Toys 🧸",
  "VOID",
  "Wormy 🪱",
  "3008 🚜",
  "Nanny",
  "The Haunted Imperial Hotel",
  "Nico's Nextbots",
  "Elmira",
  "The Mimic",
  "Doors",
  "It",
  "Murder Mystery 2",
  "Flee the Facility",
  "Evade",
  "Rainbow Friends",
  "Camp Woodland",
  "The Carnival of Horrors",
  "The Creepy House",
  "The Dark Side",
  "The Forgotten Facility",
  "The Haunted Carnival",
  "The Lost Ones",
  "Ghost Hunt",
  "Apocalypse Rising",
  "Natural Disaster Survival",
  "Survive the Killer!",
  "Dress to Impress",
  "carry a friend",
  "be a duck"
];

document.getElementById("pick-game-btn").addEventListener("click", function() {
  const randomGame = games[Math.floor(Math.random() * games.length)];
  alert(`You should play ${randomGame}!`);
});
